from datetime import datetime
from typing import Any
from typing import Literal

from pydantic import BaseModel
from pydantic import Field


ServiceType = Literal[
    "income_certificate",
    "community_certificate",
    "nativity_certificate",
    "scholarship_application",
    "pension_application",
]

Language = Literal[
    "en",
    "ta",
]

ApplicationStatus = Literal[
    "draft",
    "in_progress",
    "review",
    "confirmed",
    "submitted",
]


class ApplicationCreate(BaseModel):
    service_type: ServiceType
    language: Language = "en"


class ApplicationUpdate(BaseModel):
    language: Language | None = None

    data: dict[str, Any] | None = None


class ApplicationResponse(BaseModel):
    id: int
    service_type: str
    service_title: str
    language: str
    status: str
    progress: int
    data: dict[str, Any]
    created_at: datetime
    updated_at: datetime | None = None
    confirmed_at: datetime | None = None

    model_config = {
        "from_attributes": True,
    }


class ConversationStartRequest(BaseModel):
    service_type: ServiceType | None = None
    language: Language = "en"
    application_id: int | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class ConversationMessageRequest(BaseModel):
    session_id: str = Field(
        min_length=1,
        max_length=100,
    )

    message: str = Field(
        min_length=1,
        max_length=5000,
    )


class ConversationMessageResponse(BaseModel):
    session_id: str
    application_id: int

    user_message: str
    assistant_message: str

    current_field: str | None = None
    next_field: str | None = None

    completed: bool = False

    validation_errors: list[str] = Field(
        default_factory=list
    )


class ValidationRequest(BaseModel):
    service_type: ServiceType
    data: dict[str, Any]


class FieldValidationRequest(BaseModel):
    field: str
    value: str
    required: bool = True


class ValidationResponse(BaseModel):
    valid: bool

    errors: list[str] = Field(
        default_factory=list
    )

    warnings: list[str] = Field(
        default_factory=list
    )

    missing_fields: list[str] = Field(
        default_factory=list
    )


# ============================================================
# AI STRUCTURED RESPONSE MODELS
# ============================================================

class AIFieldUpdate(BaseModel):
    """
    Represents one field/value pair extracted by the AI.

    Example:
    {
        "field": "fullName",
        "value": "Vinu Priya"
    }
    """

    field: str
    value: str


class AIIntentResponse(BaseModel):
    """
    Structured response returned by the Gemini language-understanding layer.
    """

    intent: Literal[
        "update_fields",
        "correct_field",
        "query_form_status",
        "query_missing_fields",
        "repeat_question",
        "next_field",
        "previous_field",
        "confirm",
        "clarification",
        "unknown",
    ] = "unknown"

    # IMPORTANT:
    # This is a list instead of dict[str, str].
    #
    # Gemini Developer API does not support the dynamic
    # additionalProperties schema generated by dict[str, str].
    fields: list[AIFieldUpdate] = Field(
        default_factory=list
    )

    needs_clarification: bool = False

    clarification_question: str | None = None

    confidence: float = 0.0

    message: str | None = None

    fallback_to_client: bool = False